DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS shows;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE shows (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  rating REAL NOT NULL,
  category TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);